### ISSUE TITLE
Method called when user is invalid

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/mash#677]
The `password_dirty` method is still called when an invalid login attempt happens:

This leads to a 500 error:

```
ERROR 2020-07-02 23:11:58,474 flask.app
    Exception on /auth/login [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mash/services/api/routes/auth.py", line 103, in post
    if is_password_dirty(email):
  File "/usr/lib/python3.6/site-packages/mash/services/api/utils/users.py", line 106, in is_password_dirty
    return user.password_dirty
AttributeError: 'NoneType' object has no attribute 'password_dirty'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mash/services/api/routes/auth.py", line 103, in post
    if is_password_dirty(email):
  File "/usr/lib/python3.6/site-packages/mash/services/api/utils/users.py", line 106, in is_password_dirty
    return user.password_dirty
AttributeError: 'NoneType' object has no attribute 'password_dirty'
```

**Comment by smarlowucf** [comment]
This is fixed in staging with the database service changes. Password dirty is only checked if user is not None.
